### PR TITLE
initial work on replicate qc

### PR DESCRIPTION
**Pull request by hardingnj**
Hi @malariagen/vector-core I think this is ready for an initial look / review. 

This has now been rewritten. The intention is to run it on all samplesets, but only within each sampleset. It uses two notebooks, one with `dask` to handle parallel pairwise distance computations, and one analysis to identify problem samples.

There is a merge step to bring all genotypes into a single zarr archive first. (This pipeline is in `pipelines/combine-zarr-genotypes` of this repo.

Thoughts very welcome!

### CODE REVIEW

**Comment by podpearson** [comment]
FWIW, in Pf6 I computed the distance matrix for 5,184 batches of 100 x 100 samples, then combined those 5,184 matrices into a 7,182 x 7,182 matrix.

**Comment by hardingnj** [comment]
Updated, please see the two notebooks.

Big thanks to @alimanfoo and @slejdops on this!

**Comment by hardingnj** [comment]
Hi all, a light review on this would be appreciated- particularly @leehart @amakunin or @podpearson 

I think it should be fairly self explanatory. Happy to talk through if needed.

**Comment by leehart** [comment]
`wgs_qc` should now be `wgs_sample_qc` (https://github.com/malariagen/vector-ops/issues/793)

**Comment by amakunin** [comment]
`20190321-replicate-qc.ipynb`:
- input files & parameters used could be summarized at the top of the notebooks, e.g. next to `sampleset`
- I don't get how cluster setup at blocks 12-15 is used further. Maybe some docs on that?

`20190326-replicate-qc-analysis.ipynb`:
- fragile definition of sample replicates in block 18 (first 8 chars of sample name)
- block 20 add `;` at end

Results LGTM, but I did not try to get into the math.

**Comment by hardingnj** [comment]
Closing- superseded by notebook in vector ops

**Pull request closed without merging**
